### ISSUE TITLE
Missing property shapes in the produced SHACL

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/model2owl#203]
Hello, 

Model2OWL generates SHACL shapes for the [eProcurement Ontology (ePO)](https://github.com/OP-TED/ePO) from XMI files exported from Enterprise Architect.

However, I have identified that some properties from the UML model are not currently included in the SHACL shapes.

To investigate this, the number of property shapes produced by directly reading the Enterprise Architect file was compared against those produced by Model2OWL. The summary of my findings can be found [here](https://github.com/OP-TED/epo-tools/blob/main/outputs/missing/missingPropsSummaryCounts.md). Several discrepancies were noted.

The relation used was: 

```
    ?shape  sh:targetClass ?source ;
            sh:property  ?propertyShape .
    
    ?propertyShape a sh:PropertyShape ;
                   sh:path ?predicate .
```

I hope this information will assist in resolving the issue.

Potentially related issue: [#142](https://github.com/OP-TED/model2owl/issues/142).

**Comment by gkostkowski** [comment]
The issue has been resolved and the change has been included in the [2.3.0-rc.1](https://github.com/OP-TED/model2owl/releases/tag/2.3.0-rc.1) release. 
The paragraphs below provide explanation of the problem and the implemented solution.

**Problem**
In the former implementation of Model2Owl, the tool checked the prefix of a concept when the `generateReusedConcepts` filter was set to false. However, this logic was applied in some parts of the system even without being related to the filter. If the prefix differed from the `base-ontology-uri` variable (e.g `epo`), the concept was excluded from the generated artifacts. Since the ePO ontology uses modules like `eOrdering` and `eNotice` with prefixes such as `epo-not` and `epo-ord`, these were mistakenly considered external and were not generated.

**Solution**
New configuration variables are introduced to control artifact generation more precisely (`generateReusedConceptsSHACL`, `generateReusedConceptsOWLcore`, `generateReusedConceptsOWLrestrictions`, `generateReusedConceptsGlossary`). These variables allows individual control over whether reused concepts (considered external) are generated for each artifact type. 
Any parts of the system that previously applied the external logic without being linked to the `generateReusedConcepts` filter has been modified modified to connect with the new filters, ensuring consistent behavior. 

Additionally `includedPrefixesList` variable has been introduced. It contains a list of prefixes (e.g., `epo`, `epo-not`, `epo-ord`). These prefixes will always be treated as internal, ensuring that concepts with these prefixes are generated regardless of their designation as "reused."
