### ISSUE TITLE
wrong capitalization of cefact:code

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#83]
I think that the capitalization of cefact:code in the `range` statement is wrong because the class is spelled Capitalized:

```ttl
epo:eSubmissionPermission
        a            owl:FunctionalProperty ;
        rdfs:domain  epo:SubmissionTerm ;
        rdfs:range   <http://www.unece.org/cefact#code> .

<http://www.unece.org/cefact#Code>
        a                owl:Class ;
```

**Comment by giorgialodi** [comment]
Dear @VladimirAlexiev I am a member of the working group on the development of the e-procurement ontology. I think you are looking at some old versions of the ontology: cefact is no longer used since months. I saw other interesting comments of yours. Thanks a lot for your revisions that are very useful. Take into account that we are checking many properties of the ontology (and consequently restrictions and shapes) in order to fix things we noticed also working with real procurement data from Member States. In this sense, there will be a new version of the ontology later on this year.

**Comment by VladimirAlexiev** [comment]
Fair enough about cefact being gone.

But maybe the same bug applies in other cases?

**Comment by giorgialodi** [comment]
I am not sure but we will carefully check also with @costezki  :) Thanks again for your comments.

**Comment by VladimirAlexiev** [comment]
I checked release 2.0.1 with the following query, and indeed all classes start with uppercase:
```sparql
PREFIX owl: <http://www.w3.org/2002/07/owl#>
select * {
    ?x a owl:Class
    filter(!isBlank(?x))
} order by ?x
```
